### ISSUE TITLE
Latency check and ruRU locale

### ISSUE THREAD

**Issue by Artur91425** [xorann/oRA#1]
i added in your addon: 
1) latency module 
2) ruRU localization in all modules and libraries
3) 2 new textures - glaze and litestep
4) Waterfall-1.0 library for GUI menu. Usage: /oRA or /ora for opening GUI menu; /oRAcl or /oracl for chat commands
[oRA2.zip](https://github.com/xorann/oRA/files/863243/oRA2.zip)

add this please :)

**Comment by xorann** [comment]
Thank you very much for your additions.
