### ISSUE TITLE
Problem bei Druiden+Deutscher Client

### ISSUE THREAD

**Issue by TheMohock** [xorann/oRA#4]
In participant\CoolDown.lua hat die Abfrage nach "innervate" in Zeile 158 für Fehlermeldungen gesorgt. Die while loop kann nicht geschlossen werden, da nach "innervate" gesucht wird während im deutschen client nur "anregen" ankommt.

Das Problem lässt sich beheben indem "innervate" durch L["innervate"] ersetzt wird und in der lokalisation die Zeilen
19 ["innervate"] = true,
und
33 ["innervate"] = "anregen",
eingefügt werden.

Mich überrascht das noch nicht mehr Druiden mit lokalisierten Clients über dieses Problem gestolpert sind, vielleicht sind auch andere Sprachen betroffen.
Hier ist noch das angepasste file:
[CoolDown.zip](https://github.com/xorann/oRA2/files/1644947/CoolDown.zip)

**Comment by xorann** [comment]
Danke für den Hinweis.
Könntest du es noch einmal mit der neusten Version testen?

**Comment by xorann** [comment]
Ich gehe davon aus, dass sich dieses Problem erledigt hat. Andernfalls das Ticket einfach wieder eröffnen.
