### ISSUE TITLE
Frage: Cooldown-Anzeige

### ISSUE THREAD

**Issue by Mixuspidelix** [xorann/oRA#6]
Hallöchen, könntest Du eventuell eine Option noch einbauen die Größe der Bars/Schriftgröße zu ändern? Momentan sind diese etwas wuchtig.

Vielen lieben Dank für deine ganzen Mühen - Mixus

Ps: Noch eine weitere Sache die mir gerade in den Sinn kommt. Kann man ebenfalls eine Option einbauen die Anzeige zu sperren bzw. das gleiche für den Rezz-Monitor? Dauerhaft diese Cooldown Anzeige lesen zu müssen bzwe rezz-Moni ist ein wenig unschön :D sind allerdings nur kleinigkeiten

**Comment by xorann** [comment]
Ich habe die Optionen hinzugefügt, allerdings ohne es gross getestet zu haben.

**Comment by Mixuspidelix** [comment]
hab die neueste Version runtergeladen kurz mir ein Raid erstellt, bisher scheint alles zu funktionieren. Am Sonntag weiss ich spätestens selber mehr ob eventuell irgendwelche Error´s auftreten.

Danke Dir für die schnelle Umsetzung :)

**Comment by xorann** [comment]
Da ich nichts mehr gehört habe, gehe ich davon aus, dass alles in Ordnung ist.
