### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Vitoshka** [xorann/oRA#7]
as soon as I create a raid there is a multiple error

to index field `promotes' (a nil value)
Leader\Invite.lua:393: in function `AutoPromote'
Leader\Invite.lua:403: in function `event'
AceEvent-2.0\AceEvent-2.0.lua:430: in function <...ns\LunaUnitFrames\libs\AceEvent-2.0\AceEvent-2.0.lua:407>

  ---

**Comment by xorann** [comment]
Thanks for your report

Sadly I wasn't able to reproduce your issue. May I ask you to download the latest version and verify that the problem still occurs?
If yes, could you give me a step by step explanation how I can reproduce this?
e.g. 
1. Invite another player to a group
2. form a raid
3. you receive the error message

**Comment by Vitoshka** [comment]
Уes, that's exactly how you described the sequence of actions. The error appears in this case.

I have US client wow.

**Comment by xorann** [comment]
Have you downloaded the newest version of oRA2? There have been quite a few updates in the last days and weeks. According to the error message you posted, this has to be an issue of an older version (the line number does not match anymore).

**Comment by Vitoshka** [comment]
I'm testing the addon constantly, while I did not observe mistakes specifically on this issue...

**Comment by xorann** [comment]
I am not really sure what you are trying to tell me, but I guess this error does not appear anymore. Is this correct?

**Comment by Vitoshka** [comment]
All is well, error does not appear anymore)
